Repository sous-chefs/haproxy, pull requests merged in 2019-01, with the labels that each got.

#325 Fix acl order in listen blocks
  CHANGELOG.md
  templates/default/haproxy.cfg.erb
  test/integration/config_acl/example_spec.rb
Labels: Type: Bug

#333 Note support for stable or LTS only
  README.md
Labels: Type: Documentation

#334 update test suite versions and include all stable/LTS
  .circleci/config.yml
  .kitchen.yml
  CHANGELOG.md
Labels: Type: Maintenance
